Nc news 4 api articles articleid
KashaM767/NC-News pull request #4
Opened 2023-11-21 11:17 UTC by KashaM767

2023-11-21 11:36 UTC, nc-jonathan-mcguire requested changes
Just two bits to add please:

- [ ] Send back responses in objects with keys
- [ ] Missing a test: Status 400: Bad request, invalid article_id
E.g. GET /api/articles/notanumber

2023-11-21 11:36 UTC, nc-jonathan-mcguire commented on __tests__/seed.test.js
> +            .then(({ body }) => {
Your responses need to be returned with a key i.e. `article` in this case

2023-11-21 11:36 UTC, nc-jonathan-mcguire commented on __tests__/seed.test.js
> +});
We need a 400 test for a bad id.

2023-11-21 11:36 UTC, nc-jonathan-mcguire commented on controllers/controllers.js
> +        res.status(200).send(rows)
Your responses need to be sent back in an object with a key - i this case {article:rows}

2023-11-22 08:52 UTC, nc-mick-fay commented
Hi Kasha, happy to approve this pull request now these changes have been made. Merge into main when you're ready

2023-11-22 10:10 UTC, merged